title: "Hugo as Lindex"
#buildDrafts: true
#buildFuture: true
#buildExpired: true
#disableRSS: true
#disableSitemap: true
#metaDataFormat: "yaml"
disableKinds: ["RSS", "section", "sitemap", "robotsTXT", "404"]

contentDir: wiki
dataDir: config

taxonomies:
  project: "projects"
  material: "materials"
  customer: "customers"
  category: "categories"

    #permalinks:
    #  page: "/:section/:title/"

outputs:
  page:
  - json
  term:
  - json
  taxonomyTerm:
  - json
  taxonomy:
  - json
  home:
  - starred
  - docs_with_props
  - docs_with_title
  - indexer_info
  - docs_tasks_count
  - taxonomies
  - terms_starred

outputFormats:
  starred:
    mediaType: "application/json"
    baseName: "_index_docs_starred"
    path: "/"
  docs_with_props:
    mediaType: "application/json"
    baseName: "_index_docs_with_props"
    path: "/"
  docs_with_title:
    mediaType: "application/json"
    baseName: "_index_docs_with_title"
    path: "/"
  indexer_info:
    mediaType: "application/json"
    baseName: "_indexer_info"
    path: "/"
  taxonomies:
    mediaType: "application/json"
    baseName: "_index_taxonomies"
    path: "/"
  terms_starred:
    mediaType: "application/json"
    baseName: "_index_terms_starred"
    path: "/"
  docs_tasks_count:
    mediaType: "application/json"
    baseName: "_index_docs_tasks_count"
    path: "/"
