---
index_keys:
  types:
    type: has_many
    top_level: true
    features:
      - sub_index
  projects:
    type: has_many
    top_level: true
    features:
      - sub_index
      - count_tasks
  materials:
    type: has_many_belong_to_many
    top_level: true
    features:
      - sub_index
  customers:
    type: has_many
    top_level: true
    features:
      - sub_index
  categories:
    type: has_many
    top_level: true
    features:
      - sub_index
  archived:
    type: has_many
    top_level: false
    features:
      - sub_index
