---
title: Project
views:
  type:
    group_by: type
    except:
      - archived: is_set
  exact:
    group_by: type
    only:
      - exact: is_set
  archived:
    group_by: type
    only:
      - archived: IS_SET
